"CLP (Controlador Lógico Programável)"
Object subclass: #CLP
    instanceVariableNames: 'enderecoIP estadoComunicacao variaveis'
    classVariableNames: ''
    poolDictionaries: ''
    category: 'SCADA-Simulator'!

"SCADA (Sistema de Supervisão)"
Object subclass: #SCADA
    instanceVariableNames: 'clpsMonitorados alarmes'
    classVariableNames: ''
    poolDictionaries: ''
    category: 'SCADA-Simulator'!

"Rede Industrial"
Object subclass: #RedeIndustrial
    instanceVariableNames: 'dispositivos taxaPerdaPacotes'
    classVariableNames: ''
    poolDictionaries: ''
    category: 'SCADA-Simulator'!
